name: "exec-all"
shortDesc: "Execute a command in all of the container in a specified resource"
longDesc: >
  Execute a command in all of the containers in a specified resource
example: ""
command: "./exec-all.sh"
flags:
  - name: "container"
    shorthand: "c"
    desc: "Container name if there are multiple containers in the pod. If not included, it will use the default container."
  - name: "parallel"
    shorthand: "p"
    desc: "Number of parallel executions."
  - name: "namespace"
    shorthand: "n"
    desc: "Namespace. If not included, it will use the one specified in kubeconfig file."
